### ISSUE TITLE
Current run issues

### ISSUE THREAD

**Issue by JonLMyers** [jaredestroud/FuzzBall#14]
I receive this error when I attempt to run the fuzzer.  This was an issue even prior to adding the threading command line option.  It appears as if we just need to define requests.

soren@Kierkegaard:~/Desktop/GitHub/FuzzBall$ python Fuzzer.py --dst http://localhost --fuzz http --data "testData" --threads 10
[+] Destination is : http://localhost
[+] Scan running is : http
[+] Data being sent is : testData
[+] Number of Threads used is : [10]
Traceback (most recent call last):
  File "Fuzzer.py", line 77, in <module>
    cmd.fuzzCall(fuzz, dst, data)
  File "Fuzzer.py", line 45, in fuzzCall
    "http" :  fuzzHTTP.urlReq(str(data))
  File "/home/soren/Desktop/GitHub/FuzzBall/lib/HTTPUtils.py", line 45, in urlReq
    r = requests.get(self.url, params=data)
NameError: global name 'requests' is not defined

**Comment by jaredestroud** [comment]
I believe I fixed this in a recent commit. There was still the requests library being imported in a differ file.
