### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by JonLMyers** [jaredestroud/FuzzBall#9]
Unable to install using requirements.txt and provided install instructions using Ubuntu 14.04.3.  

OS: Ubuntu 14.04.3
Kernel: 3.19.0-47-generic
Pip Version: pip (8.0.2)

Error:

Invalid requirement: '<<<<<<< HEAD'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-8.0.2-py2.7.egg/pip/req/req_install.py", line 76, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/local/lib/python2.7/dist-packages/pip-8.0.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 3036, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python2.7/dist-packages/pip-8.0.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2967, in parse_requirements
    raise RequirementParseError("Missing distribution spec", line)
RequirementParseError: Missing distribution spec <<<<<<< HEAD

**Comment by jaredestroud** [comment]
So apparently the result of conflicting branches was pushed into the main branch which is why the issue of "<<<<<HEAD was occurring.".

I pushed the changes, let me know if this persists.

**Comment by JonLMyers** [comment]
This fixed a majority of the issues however I discovered something new.  After cleaning up some redundancies I got this error:  **No distributions matching the version for scapy-python3==0.14 (from -r requirements.txt (line 1))**

When I checked I noticed the page was 404'd.  https://pypi.python.org/pypi/scapy-python3/0.14

Is it safe to use the following instead?
https://pypi.python.org/pypi/scapy/2.3.1

**Comment by jaredestroud** [comment]
Had the same issue. I've updated the requirements page again so feel free to re-try and let me know what happens.
